spring:
  profiles:
    active: dev
---
server:
  port: 8333
spring:
  profiles: dev
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CloudSen/config-center.git
          clone-on-start: true
          timeout: 5
          force-pull: true
          # 在项目根目录下创建文件夹，必须是两层，否则空指针异常
          basedir: pull-config/local
          default-label: master
          search-paths: '{application}'
        accept-empty: false
      allow-override: false
      fail-fast: true
  devtools:
    add-properties: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8223/eureka/,http://eureka-2:8224/eureka/
  instance:
    prefer-ip-address: true
    instance-id: config-center
